// Importing necessary modules for styling in React Native
import CryptoJS from 'crypto-js'; // Import CryptoJS for encryption and decryption
import * as Keychain from 'react-native-keychain'; // Import Keychain for secure storage of encryption keys
import  {randomBytes} from 'react-native-randombytes'; // Import randomBytes for generating secure random bytes

// Get or create encryption key securely
export async function getEncryptionKey(): Promise<string> { // Function to retrieve or create an encryption key
  const credentials = await Keychain.getGenericPassword(); // Retrieve stored credentials from Keychain
  if (credentials) { // If credentials exist, return the stored password (encryption key)
    return credentials.password; // Return the stored encryption key
  } else { // If no credentials exist, generate a new encryption key
    // Generate 256-bit key (32 bytes) and encode in hex
    const keyBytes: Uint8Array = await new Promise((resolve, reject) => { // Generate a random 256-bit key
      randomBytes(32, (err, bytes) => { // Use randomBytes to generate 32 random bytes
        if (err) reject(err); // Reject the promise if there is an error
        else resolve(bytes); // Resolve the promise with the generated bytes
      });
    });
    // Convert the key bytes to hex string and store it in Keychain
    const keyHex = CryptoJS.enc.Hex.stringify(CryptoJS.lib.WordArray.create(Array.from(keyBytes))); // Convert the key bytes to hex string
    await Keychain.setGenericPassword('encryptionKey', keyHex); // Store the encryption key in Keychain
    return keyHex; // Return the newly generated encryption key
  }
}

// Encrypt and decrypt data using AES with a secure key
export function encryptData(data: string, keyHex: string): string { // Function to encrypt data using AES encryption
  const key = CryptoJS.enc.Hex.parse(keyHex); // Parse the hex string to create a CryptoJS key
  const iv = CryptoJS.lib.WordArray.random(16); // 128-bit IV (16 bytes) for AES encryption
  const encrypted = CryptoJS.AES.encrypt(data, key, { iv: iv }); // Encrypt the data using AES with the key and IV 
  // Store IV with ciphertext, separated by colon and return as a single string for decryption 
  return iv.toString(CryptoJS.enc.Hex) + ':' + encrypted.toString(); // Return the IV and ciphertext as a single string
}

// Decrypt data using AES with a secure key
export function decryptData(ciphertext: string, keyHex: string): string { // Function to decrypt data using AES encryption
  const key = CryptoJS.enc.Hex.parse(keyHex); // Parse the hex string to create a CryptoJS key
  const parts = ciphertext.split(':'); // Split the ciphertext into IV and encrypted parts
  if (parts.length !== 2) throw new Error('Invalid ciphertext format'); // Check if the ciphertext format is valid
  const iv = CryptoJS.enc.Hex.parse(parts[0]); // Parse the IV from the first part of the ciphertex, parsing is basically converting the hex string to a WordArray
  const encrypted = parts[1]; // Get the encrypted data from the second part of the ciphertext
  const decrypted = CryptoJS.AES.decrypt(encrypted, key, { iv: iv }); // Decrypt the encrypted data using AES with the key and IV
  return decrypted.toString(CryptoJS.enc.Utf8); // Convert the decrypted data to a UTF-8 string and return it
}